### ISSUE TITLE
GPU Support?

### ISSUE THREAD

**Issue by YigitDemirag** [kylemcdonald/ml-notebook#1]
Currently GPU versions of some deep-learning libraries are not supported such as Tensorflow. Is it possible to provide another ml-notebook with GPU support with proper CUDA and cudnn installation as well?

**Comment by johndpope** [comment]
fyi https://github.com/NVIDIA/nvidia-docker/issues/101

**Comment by kylemcdonald** [comment]
@johndpope @YigitDemirag do you know if it's possible at this point to run GPU-accelerated docker images on OSX? and if so, is it really difficult to setup or straightforward? i'm thinking about updating this for a workshop coming up soon.
